@startmindmap
* Trie
** 0
*** 6
**** 1
***** 2
****** 3
******* 4
******** 5
********* 6
********** 7
*********** 8 [Alice Martin]
**** 2
***** 3
****** 4
******* 5
******** 6
********* 7
********** 8
*********** 9 [Eve Moreau]
**** 3
***** 4
****** 5
******* 6
******** 7
********* 8
********** 9
*********** 0 [François Simon]
**** 4
***** 5
****** 6
******* 7
******** 8
********* 9
********** 0
*********** 1 [Grace Laurent]
**** 5
***** 6
****** 7
******* 8
******** 9
********* 0
********** 1
*********** 2 [Henri Petit]
**** 6
***** 7
****** 8
******* 9
******** 0
********* 1
********** 2
*********** 3 [Isabelle Roy]
**** 7
***** 8
****** 9
******* 0
******** 1
********* 2
********** 3
*********** 4 [Jules Blanc]
**** 8
***** 7
****** 6
******* 5
******** 4
********* 3
********** 2
*********** 1 [Bob Dupont]
***** 9
****** 0
******* 1
******** 2
********* 3
********** 4
*********** 5 [Karine Leroy]
**** 9
***** 8
****** 7
******* 6
******** 5
********* 4
********** 3
*********** 2 [Diana Lefebvre]
*** 7
**** 1
***** 2
****** 3
******* 4
******** 5
********* 6
********** 7
*********** 8 [Charlie Bernard]
******* 9
******** 8
********* 7
********** 6
*********** 5 [Luc Thomas]
**** 2
***** 3
****** 4
******* 5
******** 6
********* 7
********** 8
*********** 9 [Marie Durand]
**** 3
***** 4
****** 5
******* 6
******** 7
********* 8
********** 9
*********** 0 [Nicolas Girard]
**** 4
***** 5
****** 6
******* 7
******** 8
********* 9
********** 0
*********** 1 [Olivia Mercier]
@endmindmap
